horse-link/horse.link

- src/Navigation.tsx
- src/pages/Pools/Pools_Logic.tsx
- src/pages/Pools/Pools_View.tsx
https://github.com/horse-link/website/issues/10 closes #10
> Add pools page

- src/components/Transition.tsx
- src/hooks/useMarket.ts
- src/pages/Dashboard/Dashboard_View.tsx
There was no GH issue to reference, but this was just a minor type change along with removing a few unused imports
> Fix build, remove unused imports

- src/apis/Api.ts
- src/pages/Dashboard/Dashboard_Logic.tsx
- src/providers/Api.tsx
#31 
- add useEffect dependency to load data only once
- Api class to use baseUrl from .env
> HLK-31 fix loading market data repeatedly

- package.json
- src/components/Backdrop.tsx
- src/components/Loader/Loader_View.tsx
- src/components/ModalBody.tsx
- src/hooks/useMarket.ts
- src/index.tsx
- src/pages/Dashboard/Dashboard_View.tsx
- src/pages/Vaults/Vaults_View.tsx
- yarn.lock
- fix react warning in console
- fix broken error overlay causing transparent iframe blocking mouse event
> Fix console warning

- src/Navigation.tsx
- src/abi/MockToken.json
- src/components/ContractWriteResultCard/ContractWriteResultCard_View.tsx
- src/components/RequireWalletButton/RequireWalletButton_View.tsx
- src/pages/Back/Back_Logic.tsx
- src/pages/Back/Back_View.tsx
- src/pages/Deposit/Deposit_Logic.tsx
- src/pages/Deposit/Deposit_View.tsx
- src/pages/Vaults/Vaults_Logic.tsx
- src/pages/Vaults/Vaults_View.tsx
#37 
- Vault Deposit Page with read & write from `Vault` Contract
- Check Allowance on corresponding token first, if not enough then show "Approve" button instead
- Click approve will approve max uint amount to the vault
- refactor action button and result card from `Back` page into RequireWalletButton & ContractWriteResultCard component
- Change both Vaults List Page and Vault Deposit Page to show token's symbol instead of Vault's symbol itself
> HLK-37 Vault Deposit

- src/Navigation.tsx
- src/hooks/useTokenData.ts
- src/pages/Back/Back_View.tsx
- src/pages/Deposit/Deposit_Logic.tsx
- src/pages/Deposit/Deposit_View.tsx
- src/pages/Vault/Vault_Logic.tsx
- src/pages/Vault/Vault_View.tsx
- src/pages/Vaults/Vaults_Logic.tsx
- src/pages/Vaults/Vaults_View.tsx
Feat:
- Vault Detail Page
- On Vault list page, clicking a row navigate to vault detail page
Style:
- add hover effect on table row (Vault List Page)
- add hover effect on deposit button (Deposit Page)
- add hover effect on backing button (Backing Page)
> HLK-39 Vault Detail

- src/components/PageLayout/PageLayout_View.tsx
#51 
Fix:
- white paper external link using <a /> instead of <Link /> as Link comp will navigate instead App route only
> HLK-51 fix white paper link

- src/Navigation.tsx
- src/components/PageLayout/PageLayout_View.tsx
- src/pages/Market/Market_Logic.tsx
- src/pages/Market/Market_View.tsx
> HLK-53 Market Page

- src/hooks/useTokenApproval.ts
- src/pages/Back/Back_Logic.tsx
#64 
- Attempt to fix the error by disable function when pre-requisite parameter are not ready
> HLK-64 ENS error

- src/components/RequireWalletButton/RequireWalletButton_View.tsx
- src/pages/Back/Back_View.tsx
- src/pages/Vault/Vault_View.tsx
- tailwind.config.cjs
#63 
- adjust size and layout of cards and buttons
> HLK-63 cards and buttons ux

- src/pages/HorseRace/components/Back/Back_View.tsx
> fix: function name typo

- src/apis/Api.ts
- src/pages/Dashboard/Dashboard_Logic.tsx
- src/pages/Dashboard/Dashboard_View.tsx
- src/pages/Faucet/index.tsx
- src/types/index.ts
> HLK-88  load dashboard stats from api

- src/pages/Bets/components/BetModal.tsx
- src/pages/Bets/components/BetTable.tsx
- src/types/index.ts
#78 #79
- adjust table column
- update api response
> HLK-78 bet history

- src/components/ConnectWalletButton/ConnectWalletButton_View.tsx
- src/components/PageLayout/PageLayout_View.tsx
#81 
- center text and button
- adjust gap
- address text styling
> HLK-81 adjust nav bar layout

- .env.development
- src/apis/Api.ts
- src/hooks/useMarket.ts
- src/hooks/useMarketDetail.ts
- src/hooks/useMarkets.ts
- src/pages/HorseRace/components/Back/Back_Logic.tsx
- src/pages/HorseRace/components/Back/Back_View.tsx
- src/pages/Market/Market_Logic.tsx
- src/pages/Market/Market_View.tsx
- src/types/index.ts
#100 
- add option to fetch market data via API
- can be toggle via env `REACT_APP_REST_FOR_MARKETS`
> HLK-100 market data via API

- src/apis/Api.ts
- src/hooks/useVaultDetail.ts
- src/hooks/useVaults.ts
- src/pages/VaultList/VaultList_Logic.tsx
- src/pages/VaultList/VaultList_View.tsx
- src/types/index.ts
#101 
- fetch vault detail via API
> HLK-101 vault detail via API

- .husky/pre-commit
- src/pages/Faucet/index.tsx
#104 
- remove Goerli ETH claim button
- show token address
> HLK-104 faucet token address

- README.md
- contracts/Market.sol
Corrected spelling errors in `README` and `Market.sol`
> Typo corrections

- contracts/IVault.sol
- contracts/Market.sol
- contracts/Registry.sol
- contracts/Vault.sol
* Vault constructor sets the token symbol and name to be based on the properties of the underlying token.
* Use appropriate interface types instead of addresses
> ERC-20 vault

- package.json
- src/pages/Faucet/index.tsx
> HLK-119 copy functionality to vault addresses

- yarn.lock
> fix: build error

- src/apis/Api.ts
- src/components/ConnectWalletButton/ConnectWalletButton_View.tsx
- src/components/RunnerTable/RunnerTable.tsx
- src/pages/Dashboard/Dashboard_View.tsx
- src/pages/Dashboard/MelbourneCup/index.tsx
- src/pages/HorseRace/HorseRace_View.tsx
Add Melbourne cup race table to dashboard page
> HL-8 melbourne cup special event

- src/pages/Bets/components/BetModal.tsx
- src/pages/HorseRace/components/Back/Back_View.tsx
[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-101)
- prevent page refresh on first time button click
> HL-101 Fix modal dissappear

- src/components/WalletModal.tsx
- src/pages/Bets/components/BetModal.tsx
- src/pages/Dashboard/Dashboard_Logic.tsx
- src/pages/Dashboard/Dashboard_View.tsx
- src/pages/HorseRace/components/Back/Back_View.tsx
- src/pages/VaultList/components/Vault/Vault_View.tsx
- src/types/index.ts
[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-101)
- add prevent default to connect wallet button
- remove form tag from other pages
> HL-101 fix modal dissapear

- src/pages/Dashboard/Dashboard_View.tsx
> HL-116 Dashboard Grammar Edit 

- src/pages/Dashboard/Dashboard_View.tsx
> HL-116 Changed format of the dashboard title

- src/pages/VaultList/VaultList_View.tsx
Jas and I worked on this together
> HL-23 add descriptor to amount

- package.json
- src/pages/VaultList/components/Vault/Vault_View.tsx
- yarn.lock
[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-82)
- Changes copy for vault modal buttons
- Also adds `graphql` as a dependency for `@apollo/client` - not sure if this was just my machine but the error has a good chance of showing up again
> chore: copy changes

- src/hooks/data/useProtocolStatistics.ts
- src/types/entities.ts
- src/utils/general.ts
> fix performance stat

- src/hooks/bet/useBets.ts
- src/hooks/useSubgraph.ts
> HL-23 hotfix

- src/pages/Bets/Bets_Logic.tsx
> HL-23 hotfix 2

- src/components/PageLayout/PageLayout_View.tsx
https://dltx.atlassian.net/browse/HL-223?atlOrigin=eyJpIjoiOGE0OGJiYmFmZGJlNDE0M2JhZjc5Y2UwM2Y1N2ZlMTUiLCJwIjoiaiJ9
HL-223
Remove the white paper from the site
> HL-223 Remove white paper

- src/components/Bets/BetFilterGroup.tsx
- src/components/Bets/BetTable.tsx
- src/components/Card.tsx
- src/components/Modals/PlaceBetModal.tsx
- src/components/Vaults/VaultHistoryTable.tsx
- src/pages/Bets.tsx
- src/pages/Markets.tsx
- src/pages/Vaults.tsx
[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82/backlog?selectedIssue=HL-298)
- Add styling for phone view
- If not intuitive from the ticket -> short summary of code changes
- Include screenshots for visual UI changes
> HL-298 & HL-301 & HL-302

- src/components/Dashboard/DashboardTable.tsx
- src/pages/Dashboard.tsx
- src/utils/mocks.ts
[[Link to ticket](url)](https://dltx.atlassian.net/jira/software/projects/HL/boards/82/backlog?selectedIssue=HL-306)
I worked on making the dashboard table cell all clickable and Brett reorganised some logic with the skeleton
> HL-306 fix: dashboard table

- src/components/AccountPanel.tsx
- src/components/Tables/HistorySummaryTable.tsx
- src/components/Tables/RaceTable.tsx
- src/components/Tables/Table.tsx
- src/components/Tables/VaultSummaryTable.tsx
- src/hooks/useLocalWallet.ts
- src/test/race.spec.ts
- src/utils/races.ts
fix build error and more render issues
> UI updates placebets
